version: '3'

services:
    db:
        image: postgres
        restart: always
        container_name: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
        - 3306:3306
        expose:
        - 3306
        volumes:
            - ./data/db:/var/lib/postgresql/data

    web:
        container_name: django
        build: ./dockerfiles/django_docker
        command:
            python3 ./api/manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/code
        ports:
            - "8000:8000"
        depends_on:
            - db

    front:
        container_name: nuxt
        build: ./dockerfiles/nuxt_docker
        tty: true
        volumes:
            - ./front:/code
        ports:
            - "3000:3000"