FROM node:14.15.0-alpine

ARG WORKDIR
ARG API_URL

ENV HOME=/${WORKDIR} \
    LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    HOST=0.0.0.0 \
    API_URL=${API_URL}

WORKDIR ${HOME}

COPY package.json .
COPY . .

RUN apk update && \
    apk upgrade && \
    npm install -g n && \
    rm -rf /var/cache/apk/*

# 追加
RUN yarn install


RUN yarn run build
# ここまで

EXPOSE 80

CMD ["yarn", "start"] 